### ISSUE TITLE
perfect scrollbar

### ISSUE THREAD

**Issue by majkimajki** [creativetimofficial/light-bootstrap-dashboard-pro#21]
Is there anyway I can delete the perfect scrollbar?
It seems to cause issues, such as;
- bad heatmap recordings,
- can't use space/pagedown etc.,
- browsers seems not to understand it, after refresh it jumps back to top.

And some more.

Anyway to switch it off, and use native?

**Comment by alexandru-paduraru** [comment]
@majkimajki thank you for using our product. We've checked and the problem is not from the perfectScrollbar, the problem is coming from the structure of the product. If you **inspect element** in Chrome you will see that the page's `.wrapper` has 100vh height, which makes it full screen, while the `.main-panel` has the scroll inside it. So when you "scroll in page", you actually scroll inside `.main-panel`, not inside the body of the page. 

Please allow us 1-2 days to see how we can change the structure of the product in order to keep the perfectscrollbar and also scroll the page, not inside the `.main-panel`. In this way, the heatmaps and the other issues will be solved.

Best,
Alex

**Comment by majkimajki** [comment]
Great thanks! Waiting for you to get back to me.

Hope it wll fix all issues. 

@alexandru-paduraru maybe get back to me with a test fix version, I'll test it locally and get back to you with details, before dropping it for all users.

**Comment by alexandru-paduraru** [comment]
@majkimajki that was in our plan too :D

**Comment by dragosct10** [comment]
Hi @majkimajki! We made a few css modifications to resolve this issue and I hope this will fix everything. I will attach the partial `_sidebar-and-main-panel.scss` and what you have to do is to go in your project `assets/sass/lbd/_sidebar-and-main-panel.scss` and replace the old file with the new file, then you have to compile with [Koala](http://koala-app.com/). Make sure the output path is `HTML/assets/css/light-bootstrap-dashboard.css`.

[_sidebar-and-main-panel.scss.zip](https://github.com/timcreative/light-bootstrap-dashboard-pro/files/943722/_sidebar-and-main-panel.scss.zip)

**Comment by majkimajki** [comment]
@dragosct10 would it be possible if you supplied me with a css output?

**Comment by majkimajki** [comment]
Nevermind! Works great. Will test with heatmaps.

For now, page down and such work!
