### ISSUE TITLE
Design: Minimizing Sidebar -> Background image gets stretched out to end of content

### ISSUE THREAD

**Issue by lxlarcadelxl** [creativetimofficial/light-bootstrap-dashboard-pro#29]
Hello there,

i found something which happens in this theme. on your angular version it doesnt happen
If i minimize the Sidebar with the button at top. The background image expands as far as the page content is. 
You can test this on the example database page for example. (examples/tables/datatables.net.html)
Just use the resize Button at top and you see the behaviour.

![image](https://user-images.githubusercontent.com/23142574/30205800-450d6cb6-948a-11e7-8481-6e78818f79fe.png)

Best regards and happy coding
Marcus

**Comment by alexandru-paduraru** [comment]
@lxlarcadelxl the sidebar mini feature for the LBD HTML version was made a couple of months before the one from LBD Angular, that's why the structure is different if you can see in the HTML the sidebar is scrolling with the page, while on Angular it remains static while you scroll. 

We have in plan to add this change to LBD HTML in version v1.4.0 but we will give you a quick solution earlier. We will implement that solution for you and come back with it in 1-2 business days. Hope you understand the situation.

Best,
Alex

**Comment by dragosct10** [comment]
Hi @lxlarcadelxl! I will show you below in a few steps how to implement the new sidebar:

1. In every html pages you have to find the div with class `.sidebar` and replace the entire tag with the div with class `.sidebar` that you will find in the example page below. I will attach the `dashboard.html` page which is already modified for you to have the right example.
[dashboard.html.zip](https://github.com/creativetimofficial/light-bootstrap-dashboard-pro/files/1292284/dashboard.html.zip)

2. I will attach the scss partial `_sidebar-and-main-panel.scss` and you have to replace in `assets/sass/lbd/_sidebar-and-main-panel.scss` with the new one.
[_sidebar-and-main-panel.scss.zip](https://github.com/creativetimofficial/light-bootstrap-dashboard-pro/files/1292291/_sidebar-and-main-panel.scss.zip)

3. You have to go in `assets/sass/lbd/_misc.scss` and replace add the following lines of code: 
```html
.sidebar .nav .collapse a > span,
.sidebar .sidebar-wrapper > .nav p,
.sidebar .user .info > a > span,
.sidebar .logo a.logo-normal,
.sidebar .user .info .collapse .nav a > span {
    @include transition($fast-transition-time, $transition-linear);
}

``` 

4. Now I will attach you the file `light-bootstrap-dashboard.js` and what you have to do is to replace in `assets/js/light-bootstrap-dashboard.js` with the new one.
[light-bootstrap-dashboard.js.zip](https://github.com/creativetimofficial/light-bootstrap-dashboard-pro/files/1292298/light-bootstrap-dashboard.js.zip)

5. In the final you have to compile your scss with [Koala](http://koala-app.com/) and please be sure that your output file is `assets/css/light-bootstrap-dashboard.css`.


Hope that will help you! Please let us know if everything is working fine!

Regards,
Dragos

**Comment by lxlarcadelxl** [comment]
@dragosct10 
thanks for your help. it seems to fix it. i just added the new css properties to a custom.css file and changed the js file.
i never done recomiling scss.

Thanks it helped me lots.
Have a nice day!

**Comment by alexandru-paduraru** [comment]
@lxlarcadelxl at point 1, did you replaced the whole `div.sidebar` everything between lines 33 and 182  with the example which @dragosct10 gave to you? 

<img width="1028" alt="screen shot 2017-09-13 at 01 39 53" src="https://user-images.githubusercontent.com/2517758/30351529-8cbc2a00-9824-11e7-8eda-c27fd924d65d.png">

The new sidebar has a new structure, that's why you have to change it at all.

For point 5, did you downloaded Koala? If you don't want to work with Koala let us know and we will send you the compiled version.

Best,
Alex

**Comment by lxlarcadelxl** [comment]
@alexandru-paduraru 
But for what i shall replace class="sidebar" ? Or you mean completely replace the div sidebar element with the new div sidebar elelement from the example file.
i think i will have a look at koala.  
It seems like without koala i cannot update the files properly.
I will have a read and let you know.

Thanks for your answer.
Marcus

**Comment by alexandru-paduraru** [comment]
@lxlarcadelxl we mean to completely replace the div sidebar because on each `li > a` element there are new elements which make the structure from "Buttons" to -> "B Buttons", while the B will appear in the sidebar mini. Got it? :D

**Comment by lxlarcadelxl** [comment]
Yup now i got it. still need to get koala done :)

**Comment by lxlarcadelxl** [comment]
ok i tried it. i replaced the files and eddited the misc as described. still the image in background stretches until the end of page.
how i compile in koala ? i mean i opened the path in koala HTML\assets\sass
i copied the .js file. i edited assets/sass/lbd/_misc.scss
i copied the __sidebar-and-main-panel.scss into HTML\assets\sass\lbd
i used the dashboard html sidebar and completely removed mine to be sure i got the right structure,
the output path goes directly to the css on my webserver where it should go.

but nothing changed. i would take it online so you can check. but i dont like to link it public.

**Comment by lxlarcadelxl** [comment]
it works now as expected.. thanks a lot !

**Comment by lxlarcadelxl** [comment]
ok im sorry to bug you again. now there is a browser column to see
![image](https://user-images.githubusercontent.com/23142574/30541127-542d9c00-9c7a-11e7-8abb-53ff0259e2a9.png)

further more theres not the option anymore while in mini sidebar mode to get the poopouts now the whole sidebar opens. 

this was before the change which i really preferred:
![image](https://user-images.githubusercontent.com/23142574/30541225-bdf90e26-9c7a-11e7-9ceb-c8a2e9269b2d.png)

**Comment by lxlarcadelxl** [comment]
is the old function gone ?
![image](https://user-images.githubusercontent.com/23142574/30541949-b3cc2ad4-9c7d-11e7-955f-c478fab8a1b7.png)
where i get the links to the sections ?

at me the layout looks out of place now and i have a browser bar next to the sidebar. i use chrome.
or do i miss a file ?

![image](https://user-images.githubusercontent.com/23142574/30542035-146696d6-9c7e-11e7-8854-226d08777bc2.png)

**Comment by dragosct10** [comment]
Hi @lxlarcadelxl! Yes, the old function was removed because the sidebar now have the `position: fixed` and you can have now how many elements you want in the sidebar because the scroll is inside of the `.sidebar-wrapper` and if we let the old function this will happen: 

<img width="923" alt="screen shot 2017-09-29 at 15 05 47" src="https://user-images.githubusercontent.com/17456857/31015423-aec85d92-a528-11e7-938f-79687e59b3c8.png">

The children of the element will be hidden and this is not good. Now you must remove also the tooltips that you have to the elements because the name of the elements is displayed entirely.

Regards,
Dragos
