### ISSUE TITLE
Sweet Alert 2 not wrapping long text (like filepath) 

### ISSUE THREAD

**Issue by lxlarcadelxl** [creativetimofficial/light-bootstrap-dashboard-pro#31]
Hi ,

well another problem this time with sweet alert 2.

the text goes out of the sweet alert 2 window.

![image](https://user-images.githubusercontent.com/23142574/30322559-290137ae-97ba-11e7-8df0-9098ff92e35f.png)

i recreated a fiddle with normal sweetalert/bootstrap and jquery and the result is:
[jsfiddle](https://jsfiddle.net/lxlarcadelxl/5cdb80xo/)
![image](https://user-images.githubusercontent.com/23142574/30322597-4f65ad8a-97ba-11e7-8333-63e00ddaa38d.png)

Well i opened couple issues but still some of them still remaining open to me and i dont know how to fix them. You say compile with koala. how i do that ?
would be nice if the download files getting updated.

best regards
marcus

**Comment by alexandru-paduraru** [comment]
@lxlarcadelxl what browser did you test in? I've checked on Chrome/Firefox on Mac and the text is added correctly inside the Sweet Alert:

<img width="1038" alt="screen shot 2017-09-13 at 01 44 58" src="https://user-images.githubusercontent.com/2517758/30351685-49786b4a-9825-11e7-8027-f11dc9e70746.png">

Do you have a link that we can check?

[Koala](www.koala-app.com) is an application that let you compile SCSS files, that means you write CSS in modules and everything will be compiled into a single CSS file, in this way you write better code. More details can be found in the official doc: https://github.com/oklai/koala/wiki#docs. More about SCSS can be found here: http://sass-lang.com/

We are also doing downloaded files upgrades, but this happens when we have a list of 5-10 bugs which will create the next version, like v1.4.0. Hope you understand how we do the official updates.

Best,
Alex
