### ISSUE TITLE
Wizard is broken on small screen sizes

### ISSUE THREAD

**Issue by nzjrs** [creativetimofficial/light-bootstrap-dashboard-pro#35]
Subject says it all. Any plans or ideas to support the included wizard on small screens?

**Comment by alexandru-paduraru** [comment]
@nzjrs sorry for the late response. Can you please give us more details about the browser/os and other things that we can test in order to reproduce the issue?

Here is how it looks on our side:

<img width="374" alt="screen shot 2017-10-27 at 18 37 34" src="https://user-images.githubusercontent.com/2517758/32112468-074bbb34-bb46-11e7-8039-9baa2e083d35.png">

Best,
Alex

**Comment by nzjrs** [comment]
If you add 5 more tabs you will see what I mean.

**Comment by nzjrs** [comment]
thanks a lot!
