### ISSUE TITLE
Update Plugin

### ISSUE THREAD

**Issue by novamix** [creativetimofficial/light-bootstrap-dashboard-pro#9]
after much testing with the plugin [Extensión Export](https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/export) I had to update the bootstrap-table to the latest version, as this did not work with next .. you can upgrade everything to the latest version?

**Comment by alexandru-paduraru** [comment]
@novamix thank you for pointing out. We will update all the plugins in the next major release. Due to the high work volume that we have right now for the launch of Material Kit PRO, this update will probably come at the end of May. If you already updated your plugins please share with us what you've learnt and what were the issues that you encounter, in this way it will be easier for us to update the product and also that information will be useful for other users.

Thank you for your patience and support.

Best,
Alex

**Comment by novamix** [comment]
when will the update list?
You should divide the plugin CSS for us to update, replacing only the plugin.

**Comment by alexandru-paduraru** [comment]
@novamix we released MK Pro a couple of hours ago, so we will take care of the list in the next period of time, probably next week will come the release. You can see the SASS/CSS for any plugin that we used inside the SASS folder, there you can change/adjust and modify the CSS with anything that you want.

Please let us know if you found the SASS for the plugin.

Best,
Alex
